name = "coffee-and-code"
main = "src/index.ts"
compatibility_date = "2024-04-01"
compatibility_flags = ["nodejs_compat"]
[observability]
enabled = true

[observability.logs]
enabled = true

[vars]
PUB_NAME = "Coffee and Code"
PUB_DESCRIPTION = "A small tech publication by Daniel Morrisey."
AUTHOR_DID = "did:plc:ofkstpvgn3okv2mllx4ezkod"
DEFAULT_PDS = "https://eurosky.social"
